name: todo_modular
version: 1.0.1+2
description: Optimized Modular Flutter Todo App with modern UI, enhanced Pomodoro, and improved audio notifications.

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  sqflite: ^2.3.2
  path: ^1.9.0
  intl: ^0.20.2
  file_picker: ^6.2.0
  home_widget: ^0.6.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  shared_preferences: ^2.2.2
  csv: ^5.1.1
  audioplayers: ^5.2.1
  table_calendar: ^3.1.0
  fl_chart: ^0.66.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  # Optimized asset configuration
  assets:
    - assets/audio/
    - lib/assets/icons/
    
  # Removed custom fonts to avoid missing asset errors in CI

  # Build optimizations
  generate: true

