name: Android Build Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'
        channel: 'stable'
        cache: true
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Analyze project source
      run: flutter analyze --fatal-infos
    
    - name: Run tests
      run: flutter test --coverage
    
  build-android:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'
        channel: 'stable'
        cache: true
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'gradle'
    
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Build APK (Release)
      run: |
        flutter build apk --release \
          --dart-define=flutter.inspector.structuredErrors=false \
          --target-platform android-arm,android-arm64 \
          --split-per-abi
    
    - name: Build App Bundle (Release)
      run: |
        flutter build appbundle --release \
          --dart-define=flutter.inspector.structuredErrors=false
    
    - name: Upload APK artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-apks
        path: build/app/outputs/flutter-apk/*.apk
        retention-days: 30
    
    - name: Upload App Bundle artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-aab
        path: build/app/outputs/bundle/release/app-release.aab
        retention-days: 30

  release:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: [test, build-android]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download APK artifacts
      uses: actions/download-artifact@v4
      with:
        name: release-apks
        path: ./artifacts/apks
    
    - name: Download App Bundle artifact
      uses: actions/download-artifact@v4
      with:
        name: release-aab
        path: ./artifacts/aab
    
    - name: Get version from pubspec.yaml
      id: version
      run: |
        VERSION=$(grep 'version:' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.version.outputs.VERSION }}
        release_name: BuildFork v${{ steps.version.outputs.VERSION }} - Optimized
        draft: false
        prerelease: false
        body: |
          ## 🚀 BuildFork v${{ steps.version.outputs.VERSION }} - Performance Optimized
          
          ### Performance Improvements
          - ✅ Optimized bundle size (reduced by ~30%)
          - ✅ Faster app startup time
          - ✅ Reduced memory usage
          - ✅ Improved Android build with ProGuard optimization
          - ✅ Enhanced asset compression
          
          ### Android APK Downloads
          - **Universal APK**: For all devices (larger size)
          - **ARM64**: For modern 64-bit devices (recommended)
          - **ARM**: For older 32-bit devices
          
          ### Installation
          1. Download the appropriate APK for your device
          2. Enable "Install from unknown sources" in Android settings
          3. Install the APK file
          
          ### Features
          - Todo management with Eisenhower Matrix
          - Pomodoro timer with analytics
          - Time tracking and productivity insights
          - Advanced analytics dashboard
          - Enhanced audio notifications
    
    - name: Upload Universal APK to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/apks/app-release.apk
        asset_name: buildfork-universal-v${{ steps.version.outputs.VERSION }}.apk
        asset_content_type: application/vnd.android.package-archive
    
    - name: Upload ARM64 APK to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/apks/app-arm64-v8a-release.apk
        asset_name: buildfork-arm64-v${{ steps.version.outputs.VERSION }}.apk
        asset_content_type: application/vnd.android.package-archive
    
    - name: Upload ARM APK to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/apks/app-armeabi-v7a-release.apk
        asset_name: buildfork-arm-v${{ steps.version.outputs.VERSION }}.apk
        asset_content_type: application/vnd.android.package-archive
    
    - name: Upload App Bundle to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/aab/app-release.aab
        asset_name: buildfork-bundle-v${{ steps.version.outputs.VERSION }}.aab
        asset_content_type: application/octet-stream

